# Generated by Django 4.2.5 on 2023-09-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_shoxrux_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoxrux',
            table=None,
        ),
    ]
